branches:
  except:
    # These branches are used by Bors-NG and therefore, should not be build by Travis CI.
    # https://bors.tech/documentation/getting-started/
    - master.tmp
    - staging.tmp
    - trying.tmp

# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
# Test on Both GNU/Linux and Mac OS
matrix:
  include:

    - name: Test on GNU/Linux
      os: linux
      dist: trusty
      sudo: false
      script:
        - set -e
        - bash setup_dotfiles.sh  # Test dotfile setup
        - bash setup/setup_new_ubuntu_machine.sh  # Test Ubuntu-specific setup
        - vim +PluginInstall +qall  # Install all vim bundles

    - name: Test on Mac OS X
      os: osx
      osx_image: xcode10.2
      sudo: required
      script:
        - set -eo pipefail
        - bash setup_dotfiles.sh # Test dotfile setup
        - bash setup/setup_new_mac_machine.sh  # Test Mac OS-specific setup
        - sudo bash setup/_macos
        - vim +PluginInstall +qall  # Install all vim bundles

